### ISSUE TITLE
publishの方法

### ISSUE THREAD

**Issue by legmed** [legmed/Emergency#1]
atom→github desktop→github上にpublishしたいものを移行した（はず）なのですが、それをどうやってレポジトリ上で公開するのでしょうか？
公開したいものは1st_page.htmlから4th_page.htmlの４つです。

**Comment by kiyohara** [comment]
sync ボタンを押して同期したのであれば、自動的に公開されます。

http://midokatsu.github.io/Emergency/1st_page.html

こちらを見る限り、公開されているように見えます。

---

このコメントで問題が解決した場合は、下にある [Close Issue] というボタンをおして、この Issue をクローズしてください :smile: 
問題が解決しない場合は、追加のコメントを書き込んでください。
別の問題がある場合は、この Issue に別の問題を書き込むのではなく、右上の [New issue] というボタンで新しい Issue を作成してください。

**Comment by legmed** [comment]
ありがとうございます！公開されているようで、安心しました！

**Comment by legmed** [comment]
またまた質問なのですが…

支給された本に、google map APIの埋め込みをする前にgoogle APIs consoleにてgoogle map API v3をonにせよと記述されているのですが、google map APIs v3が見当たりません。

Google Maps Android API
Google Maps SDK for iOS
Google Maps JavaScript API
Google Places API for Android
Google Places API for iOS
Google Maps Roads API
Google Static Maps API
Google Street View Image API
Google Maps Embed API
Google Places API Web Service
Google Maps Geocoding API
Google Maps Directions API
Google Maps Distance Matrix API
Google Maps Geolocation API
Google Maps Elevation API
Google Maps Time Zone API

の中から選んでonにするのかなと解釈しましたが、どれを選んだらいいのでしょうか？

**Comment by legmed** [comment]
google_map_code.htmlにて本の通りにcodeを打ち込んでみましたが、何も表示されません。
何か情報が足りないのでしょうか？

**Comment by kiyohara** [comment]
先のコメントにも書いたとおり、内容の異なる質問は別の Issue にした方が管理しやすいです。
 #2 として新しく登録し、回答も記載しておいたのでそちらを確認してください。
この Issue 、つまり Publish されないという問題について、解決している場合は [Close] を押してください。
そうすると、私も「あ、解決できたのだな」とわかりますので :smile:
