### ISSUE TITLE
google map 本のサンプルが動かない

### ISSUE THREAD

**Issue by kiyohara** [legmed/Emergency#2]
http://midokatsu.github.io/Emergency/google_map_code.html にgoogle map 本の内容をそのまま書いたが動かない。

**Comment by kiyohara** [comment]
https://github.com/midokatsu/Emergency/blob/gh-pages/google_map_code.html#L12

この行に記載されている

``` javascript
center : new google.mapsLatLng(35.681382, 139.766084),
```

の maps の後ろに '.' が必要なはずです。
以下のようにして試してみてください。

``` javascript
center : new google.maps.LatLng(35.681382, 139.766084),
```

**Comment by legmed** [comment]
すごい！いけました！ありがとうございます！
