### ISSUE TITLE
地図上のアイコンの表示について

### ISSUE THREAD

**Issue by legmed** [legmed/Emergency#4]
google_map_code_2.htmlにてgoogle mapにアイコンが３つ配置された地図が確認できるはずなのですが、地図上にアイコンが出てきません。
何か打ち忘れているのでしょうか？

**Comment by kiyohara** [comment]
https://github.com/midokatsu/Emergency/blob/gh-pages/google_map_code_2.html#L55

にある55行目でエラーが発生しているようです。

``` javascript
marker3_txt.value = marker3.getposition();
```

ここは、以下のように Position の P を大文字にするのが正しいかと。

``` javascript
marker3_txt.value = marker3.getPosition();
```

55 行目の少し上、53行目も同様です。

**Comment by legmed** [comment]
ありがとうございます！
試してみます。

**Comment by legmed** [comment]
大文字のPにしましたが、何も変わりません…

**Comment by kiyohara** [comment]
プログラムコードとしてエラーが出ていたのですが、修正してもらったことでエラーは発生しなくなっています。
少なくともその部分は直ったということですね。

しかし、思った通りに動いていないという状況かと。
どういう動作が「思った通りの動作なのか」がわかっていないので、本のどのコードを写してみたのか教えてもらえますか。同じ本を電子書籍で持っているので、確認してみます。

紙の本と電子書籍はページがズレるので「何ページのコードか」ではなく「何章何節のコードか」を教えてください。
たとえば以下のように連絡してもらえると、どこを見ているのか明確なので助かります。

> 「2.2.4 サンプルコード」の「リスト2-2 マーカーのプロパティの動作を確認するためのコード」を書き写しました

**Comment by legmed** [comment]
第２章「 2.2.4サンプルコード」の「リスト２−２　マーカーのプロパティの動作を確認するためのコード」を書き写しました。
清原さんの例で使われたコードと同じもののようです😄

**Comment by kiyohara** [comment]
動作を確認しました。書いたコードは正しく動いています。

マーカーを表示しているのですが、その表示位置（緯度経度）が 0,0 等になっています。
このため、マーカーはアフリカ大陸のギニア湾近辺（イギリスから南下した赤道部分）に表示されています。
マップの拡大率を変えて、見てみてください。

普通に表示した場合は日本が中心となるため、ちょっと気づきにくいですね。
サンプルコードがそのように指定しているのが悪い気がしますが。。

---

なお、上記でコメントした Google Map の話とは別に、コード中に間違いを見つけました。

https://github.com/midokatsu/Emergency/blob/gh-pages/google_map_code_2.html#L93-L94

ここは、`<imput>` ではなく `<input>` ですね。
どこかのタイミングで直しておくのが良いかと。

**Comment by legmed** [comment]
！！！！！
マーカーを見つけました！ありがとうございます！

また、inputのご指摘ありがとうございます。
おっお恥ずかしい…
