### ISSUE TITLE
地図上のアイコンの表示について

### ISSUE THREAD

**Issue by legmed** [legmed/Emergency#5]

**Comment by legmed** [comment]
地図上に情報ウィンドウが出るサンプルコードをp47_sample_code.htmlとして書き写しましたが、こちらは何も表示されません。

**Comment by kiyohara** [comment]
こちらはプログラムのエラーが出ています。

おそらくですが、 p47_sample_code.html の 34 行目に '}' が必要なのではないでしょうか。

https://github.com/midokatsu/Emergency/blob/gh-pages/p47_sample_code.html#L34

まずは上記を確認してみてもらえますか。

それでも思った通りに動かない場合は、 #4 と同じように本のどのコードを写してみたのか、連絡をくださいませ。

**Comment by legmed** [comment]
}を入れてみました。
結果…　多分合っていると思われる絵が出てきました。
画像のURLを入れて変更ボタン（？）を押すとマーカーのアイコン画像が変更されるそうです。
ただ他の画像のURLが手元にないので、この変更ボタンを押すのは随分先になりそうです。

清原さん、ありがとうございます！
