### ISSUE TITLE
マップ上のアイコン表示について

### ISSUE THREAD

**Issue by legmed** [legmed/Emergency#6]
いつもお世話になっております。

42ページ、「2-2.マーカーのプロパティの動作を確認するコード」を用いて
1)座標の変更
2)アイコン画像の変更
を行ないました。

しかし、
1)天神町を指定したにもかかわらず、石川県沖にアイコンが存在する
2)アイコン画像の変更にあたり、コード中の黄色と赤色のアイコンURLが一つしか見つからず、赤色のアイコンを旗に変えることができない
また、
3)マップ上部に出てくるmarker3の座標変更をしようとしても、適用されない
の３点の壁にぶち当たり困っています。
よろしくお願いします。

**Comment by kiyohara** [comment]
質問に答える前に、いくつかお願いをさせてください。
1. Issue の書き方
   Issue を書くときには「どのファイルを変更したか」と「どの URL で動作確認をしているか」を教えてください。
   今回は、Github に残っている変更履歴を確認し、「google_map_code_2.html を変更した」「http://midokatsu.github.io/Emergency/google_map_code_2.html で動作確認をしている」と推測しました。
   しかし、あくまで推測なので、見当外れの回答をしてしまう可能性もあります。
   ですので、次回からは「どのファイルを変更したか」「どの URL で動作確認しているか」を書くように心がけてください。
2. 参考書の参照箇所の書き方
   どこのコードについての話かを書くときに、「ページ」ではなく「章」を連絡するようにしてください。
   私が確認しているのが電子書籍版ということもあり、ページを伝えてもどこのことだかわからないためです。
   今回は、リスト番号とタイトルが記載されていたので「2.2.4 サンプルコード」の「リスト2-2 マーカーのプロパティの動作を確認するためのコード」だとわかりましたが、ちょっと手間取ってしまいました。
   章番号まで伝えてもらえると、より早く回答できますのでよろしくお願いします。

**Comment by kiyohara** [comment]
質問への回答です。

1) 天神町を指定したにもかかわらず、石川県沖にアイコンが存在する

marker2 として設定したものが石川県沖に表示されています。

https://github.com/midokatsu/Emergency/blob/gh-pages/google_map_code_2.html#L23

上記のコードで表示場所が指定されています。

``` javascript
position : new google.maps.LatLng(36.556595, 135.675600),
```

二番目の数字が `135.675997` となっていますが、 `136.675997` が正解ではないかと。

2) アイコン画像の変更にあたり、コード中の黄色と赤色のアイコンURLが一つしか見つからず、赤色のアイコンを旗に変えることができない

どういう動作を期待してもらっているかちょっと曖昧なので、今のソースがどうなっているか解説しますね。

画面の上の所に `marker2.icon = [ 旗_赤.gif ] [変更]` と表示されていると思います。
この、 `旗_赤.gif` を `旗_黒.gif` と書き換えてから [変更] ボタンを押してみてください。
marker2 の画像が赤い旗から黒い旗に変更されると思います。

3) マップ上部に出てくるmarker3の座標変更をしようとしても、適用されない

marker3 については、指定した緯度経度に設定するという機能ではなく、現在 marker3 が表示されている場所の緯度経度を表示するというコードになっています。
marker3 はギニア湾に表示されていますが、これはドラッグアンドドロップできるものになっています。
marker3 をドラッグアンドドロップで移動させてから、画面上部にある

`marker3の位置 [ (0.2, 0.20000000000004547) ] [取得]`

この表示の [取得] ボタンを押してみてください。

`[ (0.2, 0.20000000000004547) ]`

こう表示されている部分の内容が変更され、 marker3 が表示されている場所の緯度経度が表示されます。

**Comment by legmed** [comment]
清原さん、お忙しい中お手数をおかけしてしまい申し訳ありません。
次回より気をつけます。

**Comment by legmed** [comment]
詳しい説明をありがとうございます！
ご指摘の通り、「2.2.4 サンプルコード」の「リスト2-2 マーカーのプロパティの動作を確認するためのコード」を用いて、
「google_map_code_2.html」「http://midokatsu.github.io/Emergency/google_map_code_2.html 」で動作確認をしています。

２）ですが、黄色と赤色のアイコンを、google_map_code_2.htmlのコード(atom)上で、赤色と黒色の旗にチェンジしたいのです。
コードを確認すると、黄色のアイコンはURL（「google_map_code_2.html」の25行目）によって指定されていることが分かりました。ですので、黄色のアイコンは赤色の旗に変えることができました。
しかし、赤色のアイコンが何によって指定され存在しているのか分からないので、黒色の旗に変えることができません。
赤色のアイコンがどこで指定されているのか教えて下さい。

**Comment by kiyohara** [comment]
「赤色のアイコン」は、コード上「なにも指定しない」場合に表示されます。

たとえば、今、赤い旗を指定しているコード ( https://github.com/midokatsu/Emergency/blob/gh-pages/google_map_code_2.html#L22-L25 ) は以下のようになっていると思います。

``` javascript
var marker2 = createMarker({
  position : new google.maps.LatLng(36.556595, 135.675600),
  map : mapCanvas,
  icon : "旗_赤.gif"
});
```

この、 `icon: "旗_赤.gif"` という指定が、アイコンを指定している部分です。
試しにこの `icon: "旗_赤.gif"` を、以下のように削除してみてください。
（ `map : mapCanvas,` の `,` も削除してください）

``` javascript
var marker2 = createMarker({
  position : new google.maps.LatLng(36.556595, 135.675600),
  map : mapCanvas
});
```

すると、いままで旗が表示されていたところが、「赤色のアイコン」になると思います。
逆に、今はなにも設定していない marker1 のコード ( https://github.com/midokatsu/Emergency/blob/gh-pages/google_map_code_2.html#L17-L20 ) をこのように変更してみてください。
（ `map : mapCanvas` の後ろに `,` を追加するのを忘れずに）

``` javascript
var marker1 = createMarker({
  position : new google.maps.LatLng(36.556595, 136.675997),
  map : mapCanvas,
  icon : "旗_黒.gif"
});
```

こうすることで、marker1 を黒色の旗に変更できるはずです。

このように、マーカーのアイコンは指定することもできるし、特に指定しないこともできるということです。
特に指定しない場合には、Google が既定のアイコンを指定してくれている、とも言えます。
このように「特別に指定しない場合に使われる勝手に指定される値」を「デフォルトの値」と言います。
会話の中では「Google Map のマーカーに使われるデフォルトのアイコンは赤色のアイコン」というように使われます。参考まで。

**Comment by legmed** [comment]
なるほど！！！
分かりやすい説明をありがとうございます！
とてもよく分かりました！
