### ISSUE TITLE
ありがとうございました！

### ISSUE THREAD

**Issue by legmed** [legmed/Emergency#9]
直接お礼が言えなかったので、ここで…

大変お世話になりました。
ありがとうございました！
半年を通してアプリを学び、色んなことを経験させていただきました。
パソコンも少しだけ身近になりました。
本当にありがとうございます！
今後も分からないところを教えてください。。＞＜

**Comment by kiyohara** [comment]
今日はせっかくの発表の日でしたのに、中座してしまい失礼しました。
発表内容を聞きながら、形になってきた過程を思い出し、すこし感動しました :+1: 

本 Github のプロジェクトは継続して見ていくつもりなので、何かあればまた Issue を立ててください。
合間をみてコメントするようにしますね。
